Document option incompatiblities
schweikert/fping pull request #337
Opened 2024-07-23 10:55 UTC by moritz

The documentation for `--count` already mentions that it modifies the output.

This changes the documentation for `--alive` and `--unreach` to explicitly state that they don't work together with `--count`.

2024-07-27 14:40 UTC, auerswal requested changes
Thanks for the pull request!

I'd say that the documentation changes should account for more details:
 * Both options -c and -C override -a and -u.
 * Using "incompatible" is rather vague, "override" is more precise.
 * References to other options in the fping man page usually use the short version only (if applicable).
 * I would rather have this added to the same line as the existing description instead of putting it in a new paragraph.

Would you like to adjust your pull request, or would you prefer me to implement my suggestion?

2024-07-27 14:40 UTC, auerswal commented on doc/fping.pod
> +Not compatible with option B<--count> / B<-c>.
How about adding something like "(Option B<-c> or B<-C> overrides B<-a>)"? This could start in the same line as the existing description.

2024-07-27 14:40 UTC, auerswal commented on doc/fping.pod
> +Not compatible with option B<--count> / B<-c>.
How about adding something like "(Option B<-c> or B<-C> overrides B<-u>)"? This could start in the same line as the existing description.

2024-07-27 17:21 UTC, moritz commented
I'd be happy if you adjusted it to your preference before merging.

2024-08-04 15:25 UTC, auerswal commented
This has been replaced by merging #338.

2024-08-04 15:25 UTC, closed without merging